### ISSUE TITLE
能用于mysql实例之间的数据校验吗

### ISSUE THREAD

**Issue by dbaCT** [WentaoJin/tichecker#1]
我们内部有 `主从 -> MGR` 这样的链路，通过传统复制进行的数据同步。我们想校验集群间的数据一致性，但下游是 MGR，所以没法使用 `pt-table-checksum`。
请问，这个工具能用在上述场景中吗，谢谢！

**Comment by wentaojin** [comment]
> 我们内部有 `主从 -> MGR` 这样的链路，通过传统复制进行的数据同步。我们想校验集群间的数据一致性，但下游是 MGR，所以没法使用 `pt-table-checksum`。 请问，这个工具能用在上述场景中吗，谢谢！

不好意思，不可行，因为其是基于下游 tidb 统计信息 Buckets 划分比对 chunk 范围用于上下游对比
